version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ganteng
      MYSQL_DATABASE: food_gamification
      MYSQL_USER: ali
      MYSQL_PASSWORD: ganteng
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ganteng
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: .
    container_name: food_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://ali:ganteng@db:3306/food_gamification"
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  db_data:
